- hosts: all
  remote_user: root
  gather_facts: no
  tasks:
      - name: Install python
        raw: "apt-get update -y && apt-get install {{ python_package }} -y"
        when: install_python

- hosts: docker_registry
  remote_user: root
  roles:
      - lexrus.ansible-role-docker
      - role: docker-registry
      - geerlingguy.apache

- hosts: executor
  remote_user: root
  roles:
      - lexrus.ansible-role-docker
      - geerlingguy.apache
      - role: executor
      - role: nfs

- hosts: cluster_master
  remote_user: root
  roles:
      - role: mesos-master
      - role: chronos

- hosts: cluster_nodes
  remote_user: root
  roles:
      - lexrus.ansible-role-docker
      - role: mesos-slaves
      - role: nfs-cluster-clients
      - role: prometheus-node-exporter
      - role: cadvisor

- hosts: monitor
  remote_user: root
  roles:
      - geerlingguy.apache
      - role: prometheus

- hosts: editor
  remote_user: root
  roles:
      - geerlingguy.apache
      - role: editor
