- debug: var=data_share

- name: Ensure shared directory for data
  file:
      dest: "{{ data_share }}"
      state: directory

- name: Ensure shared directory for tools
  file:
      dest: "{{ tools_share }}"
      state: directory

- name: Install nfs-server
  apt:
      name: nfs-kernel-server
      state: latest

- name: Configure nfs exports
  template:
      src: exports.j2
      dest: /etc/exports
      force: yes
  notify:
      - reload exports
      - restart nfs-server
